#!/bin/bash

echo "Guaptalk Forum Setup Script"
echo "=========================="
echo ""
echo "This script will help you set up the Guaptalk NodeBB forum."
echo ""
echo "Prerequisites:"
echo "- Node.js (already installed)"
echo "- Redis or MongoDB database"
echo ""
echo "Please install Redis first:"
echo "  macOS: brew install redis && brew services start redis"
echo "  Ubuntu: sudo apt-get install redis-server"
echo "  Other: Visit https://redis.io/download"
echo ""
echo "After installing Redis, run:"
echo "  ./nodebb setup"
echo ""
echo "During setup, use these settings:"
echo "- URL: http://localhost:4567 (or your domain)"
echo "- Database: redis"
echo "- Administrator username: admin"
echo "- Administrator email: your-email@example.com"
echo ""
echo "After setup completes, run:"
echo "  ./nodebb start"
echo ""
echo "Then visit http://localhost:4567 to see your forum!"
echo ""
echo "The Guaptalk theme has been installed and will be available in the admin panel."
echo "Go to Admin > Appearance > Themes to activate it."